# --------------------
# (main) startMidi.py
# v0.3.5 - 2019/8/12
# Double-click this to launch the program!
# --------------------

import sys
sys.path.append("..")

import os

import mcpi.minecraft as mmc
import tools
from setSystem import setRedstoneSystem
from constructSystem import constructRedstoneSystem

mc = tools.start(0)

# --------------------
# runTest
# --------------------

def runTest(path):
    """Sync this up when adding or changing mtests"""
    if path == "Promenade.mid":
        path = os.getcwd() + "\\music\\tests\\mtests\\Promenade.mid"
    return path

# --------------------
# main
# --------------------

if __name__ == "__main__":
    
    mc.postToChat("")
    mc.postToChat("Music Lab v0.3.5 initiated!")
    mc.postToChat("")
    mc.postToChat("Please input (in-game) the path of the midi file you want to realize, beginning with an additional hyphen: (i.e. -C:\\Raspy\\test.mid or -/Users/<your-name>/Documents/test.mid)")
    mc.postToChat("")

    while True:
        posts = mc.events.pollChatPosts()

        if len(posts) > 0:
            try:
                zeroOrNot = int(posts[0].message)
            except ValueError:
                mc.events.clearAll()
            else:
                mc.events.clearAll()
                if zeroOrNot == 0:
                    mc.postToChat("")
                    mc.postToChat("Process aborted.")
                    sys.exit(0)
                else:
                    mc.postToChat("")
                    mc.postToChat("The number isn't 0. Do you wish to abort?")
                    mc.postToChat("Please input a valid path, or input 0 to abort the process.")
                    mc.postToChat("")
                    continue
            
            pathWithHyphen = posts[0].message
            path = pathWithHyphen.lstrip("-")

            path = runTest(path)

            try:
                configurationList = setRedstoneSystem(path, mc)
            except FileNotFoundError:
                mc.events.clearAll()
                mc.postToChat("")
                mc.postToChat("Cannot find a file at your path, or your input isn't indicating a path.")
                mc.postToChat("Please input another path, or input 0 to abort the process.")
                mc.postToChat("")
                continue
            except PermissionError:
                mc.events.clearAll()
                mc.postToChat("")
                mc.postToChat("Uh-oh, seems like the program doesn't have the permission to visit that path. Try putting the file in a different folder.")
                mc.postToChat("Please input another path, or input 0 to abort the process.")
                mc.postToChat("")
                continue
            except IndexError:
                mc.events.clearAll()
                mc.postToChat("")
                mc.postToChat("The file you requested isn't midi file, or your midi file cannot be processed at the moment. Sorry!")
                mc.postToChat("Please input another path, or input 0 to abort the process.")
                mc.postToChat("")
                continue
            except ValueError as ve:
                mc.postToChat("")
                mc.events.clearAll()
                if ve.args[0] == "Nothing":
                    mc.postToChat("There's literally nothing in your midi file. Therefore we cannot proceed.")
                    mc.postToChat("Please input another path, or input 0 to abort the process.")
                    mc.postToChat("")
                    continue
                if ve.args[0] == "Too many voices":
                    mc.postToChat("Sorry, your midi file contains moments of too many notes playing. Redstone music system generated by this program cannot handle that.")
                    mc.postToChat("Please input another path, or input 0 to abort the process.")
                    mc.postToChat("")
                    mc.postToChat("Note: If this warning comes after the program asks you the tempo, you can retry this file and input a different tempo to see if it works.")
                    mc.postToChat("")
                    continue
            else:
                mc.events.clearAll()
                constructRedstoneSystem(configurationList, mc)
                break
